In [ ]:
import numpy as np
import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('datasets/insurance_data.csv')
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [8]:
df.shape

(28, 3)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df['bought_insurance'], test_size=0.2, random_state=42)

In [7]:
len(X_train)

22

In [11]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

x_test_scaled = X_test.copy()
x_test_scaled['age'] = x_test_scaled['age']/100

In [12]:
X_train_scaled.head()

     age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])